spring:
  application:
    name: crm-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: customer-service
              uri: http://localhost:8201
              predicates:
                - Path=/services/customer/**
              filters:
                - StripPrefix=2
            - id: account-service
              uri: http://localhost:8202
              predicates:
                - Path=/services/account/**
              filters:
                - StripPrefix=2
            - id: workflow-service
              uri: http://localhost:8401
              predicates:
                - Path=/services/workflow/**
              filters:
                - StripPrefix=2
            - id: master-setup-service
              uri: http://localhost:8501
              predicates:
                - Path=/services/mastersetup/**
              filters:
                - StripPrefix=2
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8180/realms/crm-realm
server:
  port: 8100